### ISSUE TITLE
Cannot build sharktools in Mac OS X

### ISSUE THREAD

**Issue by hasonhai** [armenb/sharktools#3]
Hi,
I try to use sharktools with Matlab on Mac Mountain Lion. The configure command "seems" to work correctly but the make command still generate error.
Here is the ./configure output:
# 

dhcp129-192:sharktools hasonhai$ ./configure --with-mex=/Applications/MATLAB_r2012a.app/bin/mex --with-libwireshark=/opt/local/lib/libwireshark.dylib --with-macports=/opt/local --with-wireshark-src=/Users/hasonhai/wireshark --enable-matshark
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for vprintf... yes
checking for _doprnt... no
checking for ranlib... ranlib
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB_2_0... yes
checking for MacOSX... yes
checking for fink... no
checking for MacPorts... yes: /opt/local/bin/port
checking for Wireshark in MacPorts... yes: /opt/local/bin/wireshark
checking to see if Wireshark.org's dmg is installed (we can't use it, but good to know)... yes: /Applications/Wireshark.app/Contents/Resources/bin/wireshark
checking for /opt/local/lib/libwireshark.dylib... yes
checking the word size of libwireshark... found 64-bit libwireshark!
checking for Linux... no
checking for pkg-config... /opt/local/bin/pkg-config
checking for GLIB - version >= 2.0.0... yes (version 2.34.3)
checking for wireshark... /opt/local/bin/wireshark
checking for /Users/hasonhai/wireshark... yes
checking for /Users/hasonhai/wireshark/config.h... yes
Wireshark version detected: 1 #define VERSION_MAJOR 1 #define VERSION_MICRO 1 #define VERSION_MINOR 9.9 #define VERSION_MAJOR 1 #define VERSION_MICRO 1 #define VERSION_MINOR 9.1 #define VERSION_MAJOR 1 #define VERSION_MICRO 1 #define VERSION_MINOR 9
./configure: line 5233: test: too many arguments
./configure: line 5235: test: too many arguments
configure: WARNING: wireshark version is really
checking for /Applications/MATLAB_r2012a.app/bin/mex... yes
MEXARCH=-maci64
MEXEXT=mexmaci64
configure: creating ./config.status
config.status: creating src/Makefile
config.status: creating Makefile
config.status: executing depfiles commands
# 

And here is the generated error from "make":
# 

dhcp129-192:sharktools hasonhai$ make
Making all in src
gcc -o sharktools_cfile.o -c -g -Wall -DHAVE_CONFIG_H -fPIC -O2 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_VPRINTF=1 -DDEBUG=0 -DWIRESHARK_1_8_0=1 -I. -I/Users/hasonhai/wireshark -I/Users/hasonhai/wireshark/wiretap -D_REENTRANT -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include sharktools_cfile.c 
gcc -o sharktools_core.o -c -g -Wall -DHAVE_CONFIG_H -fPIC -O2 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_VPRINTF=1 -DDEBUG=0 -DWIRESHARK_1_8_0=1 -I. -I/Users/hasonhai/wireshark -I/Users/hasonhai/wireshark/wiretap -D_REENTRANT -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include sharktools_core.c 
sharktools_core.c: In function ‘get_field_data’:
sharktools_core.c:579: error: ‘data_source’ undeclared (first use in this function)
sharktools_core.c:579: error: (Each undeclared identifier is reported only once
sharktools_core.c:579: error: for each function it appears in.)
sharktools_core.c:579: error: ‘src’ undeclared (first use in this function)
sharktools_core.c: In function ‘process_packet’:
sharktools_core.c:990: warning: implicit declaration of function ‘wtap_pseudoheader’
sharktools_core.c:990: warning: initialization makes pointer from integer without a cast
sharktools_core.c:1006: warning: passing argument 4 of ‘frame_data_set_before_dissect’ from incompatible pointer type
sharktools_core.c:1006: warning: passing argument 5 of ‘frame_data_set_before_dissect’ from incompatible pointer type
sharktools_core.c:1020: warning: passing argument 2 of ‘epan_dissect_run’ from incompatible pointer type
sharktools_core.c:1033: error: too many arguments to function ‘frame_data_set_after_dissect’
make[1]: **\* [sharktools_core.o] Error 1
make: **\* [all-recursive] Error 1
# 

Thank you very much!

**Comment by mchccc** [comment]
I'm afraid that's no OSX's fault: those issues come straight from updates to Wireshark's code pushed in 1.9.x.
I tried looking into it, but the conversion between nstime and frame_data does not seem trivial (unlike the pseudoheader stuff, which was apparently just moved around and seem to be easily reachable from within the capture_file struct).
I just found out about this tool and I'm all excited about testing it out, so I rolled back to Wireshark 1.8.6 for the time being; I'd love to help more, tho, so I'd be interested in carrying on with this conversation.
